QQuadra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reservas/', include('reservas.urls')),
    path('exames/', include('exames.urls')),
    path('perfil/', include('perfil.urls')),
    path('gerenciar/', include('gerenciar.urls')),
]

accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('list/', views.list_users, name='list'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    path('menu-reservas/', views.menu_reservas_admin, name='menu-reservas'),
    path('list-reservas-admin/', views.reservas_espaco_admin, name='menu-reservas-admin'),
    path('reserva/delete/<int:pk>', views.delete_reserva, name='delete-reserva'),
    path('list-reservas-exames-admin/', views.reservas_exames_admin, name='menu-reservas-exames-admin'),
    path('reserva-exame/delete/<int:pk>', views.delete_reserva_exames, name='delete-reserva-exame'),
    path('list-reservas/', views.reservas_espaco, name='list-reservas'),
    path('list-reservas-exames/', views.reservas_exames, name='menu-reservas-exames'),
    path('reserva-normal/delete/<int:pk>', views.delete_reserva_normal, name='delete-reserva-normal'),
    path('reserva-exame-normal/delete/<int:pk>', views.delete_reserva_exames_normal, name='delete-reserva-exame-normal'),
]

exames/urls.py
from django.urls import path

from . import views

app_name = 'exames'
urlpatterns = [        
    path('', views.exames, name='index'),
    path('dias/<int:pk>', views.detail_dia, name='detail-dia'),
    path('exame/confirmar/<int:pk>', views.create_reserva, name='create-reserva'),
]

gerenciar/urls.py
from django.urls import path

from . import views

app_name = 'gerenciar'
urlpatterns = [        
    path('', views.gerenciar, name='index'),
    path('resetar/', views.resetar, name='resetar'),
    path('resetar/exames/', views.resetar_exames, name='resetar-exames'),
    path('atualizar/', views.atualizar, name='atualizar'),
    path('atualizar/exames/', views.atualizar_exames, name='atualizar-exames'),
    path('gerenciar/modalidades/', views.modalidades_list, name='lista-modalidades'),
    path('gerenciar/material/<int:pk>', views.material_list, name='lista-material'),
    path('gerenciar/material/estoque/<int:pk>', views.material_estoque, name='estoque-meterial'),
    path('gerenciar/material/estoque/update/<int:pk>', views.update_estoque, name='update-estoque'),
    
]

gerenciar/models.py
from django.db import models

# Create your models here.

gerenciar/forms.py
from django.forms import ModelForm
from accounts.models import EstoqueMaterial

class PostForm(ModelForm):
    class Meta:
        model = EstoqueMaterial
        fields = [
            'quantidade',
        ]
        labels = {
            'quantidade': 'Quantidade',
        }

gerenciar/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from accounts.models import Usuario,Clube, EspacoEsportivo, Dia,Horario,Modalidade,Dia_Exames,Horario_Exames,TipoMaterial,EstoqueMaterial
from datetime import timedelta
import datetime as dt
from django.utils import timezone
from accounts.decorators import allowed_users
from .forms import PostForm



def atualizar_dias(dias):
    today = timezone.now().date()
    espacos = EspacoEsportivo.objects.all()
    desatualizado=False
    for dia in Dia.objects.all():
        if today > dia.dia:
            Dia.objects.filter(id=dia.id).delete()
            desatualizado=True
    if desatualizado:
        for espaco in espacos:
            today = timezone.now().date()
            today = today + dt.timedelta(days=dias-1)
            dia = Dia.objects.create(espaco=espaco,dia=today) 
            start = espaco.clube.horario_inicial  
            while start != espaco.clube.horario_final:
                
                Horario.objects.create(dia=dia,horario=start)
                start = (dt.datetime.combine(dt.date(1,1,1), start) + dt.timedelta(hours=1)).time()
    return



def atualizar_dias_exames(dias):
    today = timezone.now().date()
    clubes = Clube.objects.all()
    desatualizado=False
    for dia in Dia_Exames.objects.all():
        if today > dia.dia:
            Dia_Exames.objects.filter(id=dia.id).delete()
            desatualizado=True
    if desatualizado:
        for clube in clubes:
            today = timezone.now().date()
            today = today + dt.timedelta(days=dias-1)
            dia = Dia_Exames.objects.create(clube=clube,dia=today)
            start = clube.horario_inicial  
            while start != clube.horario_final:
                
                Horario_Exames.objects.create(dia=dia,horario=start)
                start = (dt.datetime.combine(dt.date(1,1,1), start) + dt.timedelta(hours=1)).time()
    return



@login_required(redirect_field_name='login')
@allowed_users(allowed_roles=['admin'])
def gerenciar(request):
    
    return render(request, 'gerenciar/gerenciar.html')



@login_required(redirect_field_name='login')
def resetar(request):
    create_dias(63)
    return render(request, 'gerenciar/resetar.html')



@login_required(redirect_field_name='login')
def resetar_exames(request):
    create_dias_exames(63)
    return render(request, 'gerenciar/resetar.html')



@login_required(redirect_field_name='login')
def atualizar(request):

    atualizar_dias(63)
    return render(request, 'gerenciar/resetar.html')



@login_required(redirect_field_name='login')
def atualizar_exames(request):
    
    atualizar_dias_exames(63)
    return render(request, 'gerenciar/resetar.html')



def create_dias(dias):
    Dia.objects.all().delete()
    espacos = EspacoEsportivo.objects.all()
    for espaco in espacos:
        today = timezone.now().date()
        for i in range(dias):
            dia = Dia.objects.create(espaco=espaco,dia=today)  
            start = espaco.clube.horario_inicial  
            while start != espaco.clube.horario_final:
                
                Horario.objects.create(dia=dia,horario=start)
                start = (dt.datetime.combine(dt.date(1,1,1), start) + dt.timedelta(hours=1)).time()
                
            today = today + dt.timedelta(days=1)



def create_dias_exames(dias):
    Dia_Exames.objects.all().delete()
    clubes = Clube.objects.all()
    for clube in clubes:
        today = timezone.now().date()
        for i in range(dias):
            dia = Dia_Exames.objects.create(clube=clube,dia=today)  
            start = clube.horario_inicial  
            while start != clube.horario_final:
                
                Horario_Exames.objects.create(dia=dia,horario=start)
                start = (dt.datetime.combine(dt.date(1,1,1), start) + dt.timedelta(hours=1)).time()
                
            today = today + dt.timedelta(days=1)



def modalidades_list(request):
    if request.user.is_authenticated:
        user = request.user
        clube = user.clube
        context = {'clube': clube,
                    }
    return render(request, 'gerenciar/lista-modalidades.html', context)



def material_list(request, pk):
    if request.user.is_authenticated:
        user = request.user
        clube = user.clube
        modalidade = get_object_or_404(Modalidade,pk=pk)
        materials = TipoMaterial.objects.filter(modalidade=modalidade.id)
        context = {'clube': clube,
                    'modalidade':modalidade,
                    'materials':materials}
    return render(request, 'gerenciar/lista-materiais.html', context)



def material_estoque(request, pk):
    if request.user.is_authenticated:
        user = request.user
        clube = user.clube
        estoque = EstoqueMaterial.objects.filter(tipo_material=pk,clube=clube.id)
        context = {'clube': clube,
                    'estoque':estoque,}
    return render(request, 'gerenciar/estoque.html', context)



@login_required(redirect_field_name='login')
@allowed_users(allowed_roles=['admin'])
def update_estoque(request, pk):
    estoque = get_object_or_404(EstoqueMaterial, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            estoque.quantidade = form.cleaned_data['quantidade']            
            estoque.save()
            return HttpResponseRedirect(
                reverse('gerenciar:estoque-meterial', args=(estoque.tipo_material.id, )))
    else:
        form = PostForm(
            initial={
                'quantidade': estoque.quantidade,
            })

    context = {'estoque': estoque, 'form': form}
    return render(request, 'gerenciar/update-estoque.html', context)

gerenciar/templates/gerenciar/estoque.html
{% extends 'base.html' %}

{% block title %}
Estoque de Material
{% endblock title %}

{% block content %}
<h1>Estoque de Materiais</h1>
<div class = "caixinha1">
    <li><b>Clube:</b> {{ clube.name | safe}}</li>
    {% if estoque %}
        <li><b>Modalidade:</b> {{ estoque.0.tipo_material.modalidade.name | safe}}</li>
    {% endif %}
</div>
<br></br>

{% if estoque %}
    <table>
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Quantidade</th>
                <th>Atualizar</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ estoque.0.tipo_material.name | safe}}</td>
                <td>{{ estoque.0.quantidade | safe}}</td>
                <td><a href="{% url 'gerenciar:update-estoque' estoque.0.id %}">Atualizar</a></td>
            </tr>  
        </tbody>
    </table>
{% else %}
    <h2>Não existe estoque para este tipo de material</h2>
{% endif %}

{% endblock content %}

gerenciar/templates/gerenciar/gerenciar.html
{% extends 'base.html' %}

{% block title %}
Gerenciar
{% endblock title %}

{% block content %}

<h1>Menu de Funções do Adminitrador</h1>

<div class="functionMenu1">
    <div class="function">
        Verificar Usuarios <br>
        <a href="{% url 'accounts:list' %}"><img src="https://i.imgur.com/sUX9TVd.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Editar Reservas <br>
        <a href="{% url 'accounts:menu-reservas' %}"><img src="https://i.imgur.com/uTvysWr.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Editar Materiais <br>
        <a href="{% url 'gerenciar:lista-modalidades' %}"><img src="https://i.imgur.com/No7mqY8.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Atualizar Reservas <br>
        <a href="{% url 'gerenciar:atualizar' %}"><img src="https://i.imgur.com/vUJHs0B.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Atualizar Exames <br>
        <a href="{% url 'gerenciar:atualizar-exames' %}"><img src="https://i.imgur.com/vUJHs0B.png" width="100" height="100" alt="Reservas"></a>
    </div>
    {% if user.is_superuser %}
        <div class="function">
            Resetar Reservas <br>
            <a href="{% url 'gerenciar:resetar' %}"><img src="https://i.imgur.com/vUJHs0B.png" width="100" height="100" alt="Reservas"></a>
        </div>
        <div class="function">
            Resetar Exames <br>
            <a href="{% url 'gerenciar:resetar-exames' %}"><img src="https://i.imgur.com/vUJHs0B.png" width="100" height="100" alt="Reservas"></a>
        </div>
    {% endif %}
</div>
{% endblock content %}

gerenciar/templates/gerenciar/lista-materiais.html
{% extends 'base.html' %}

{% block title %}
Estoque de Material
{% endblock title %}

{% block content %}
<br>

<h1>Estoque de Materiais</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
<li><b>Modalidade:</b> {{modalidade.name | safe}}</li>


</div>
<h3>Selecione um Material:</h3>

    {% for material in materials.all %}
        <div class="caixinha3">
            <div class="function">
        {{material.name}} <br>
        <a href="{% url 'gerenciar:estoque-meterial' material.id  %}"><img src="{{ material.foto  }}" width="100" height="100" alt="{{material.name}}"></a>
             </div>
         </div>
        <br></br>  
    {% endfor %}

{% endblock content %}

gerenciar/templates/gerenciar/lista-modalidades.html
{% extends 'base.html' %}

{% block title %}
Estoque de Material
{% endblock title %}

{% block content %}
<br>

<h1>Estoque de Materiais</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
</div>
<h3>Selecione uma Modalidade:</h3>

<div class="functionMenu">
    {% for modalidades in clube.modalidades.all %}
        <div class="function">
            {{modalidades.name}} <br>
            <a href="{% url 'gerenciar:lista-material' modalidades.id %}"><img src="{{ modalidades.icon_url  }}" width="100" height="100" alt="{{modalidades.name}}"></a>
        </div>  
    {% endfor %}
</div>

{% endblock content %}

gerenciar/templates/gerenciar/resetar.html
{% extends 'base.html' %}

{% block title %}
Resetar
{% endblock title %}

{% block content %}
<h1>RESETADO</h1>
<a href="{% url 'gerenciar:index' %}"><h1>Voltar</h1></a>

{% endblock content %}

gerenciar/templates/gerenciar/update-estoque.html
{% extends 'base.html' %}

{% block title %}
Estoque de Material
{% endblock title %}

{% block content %}
<h2>Atualizar Estoque {{ estoque_material.tipo_material }}</h2>
<form method="POST" action="{% url 'gerenciar:update-estoque' estoque.tipo_material.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}