QQuadra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reservas/', include('reservas.urls')),
    path('exames/', include('exames.urls')),
    path('perfil/', include('perfil.urls')),
    path('gerenciar/', include('gerenciar.urls')),
]

accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('list/', views.list_users, name='list'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    path('menu-reservas/', views.menu_reservas_admin, name='menu-reservas'),
    path('list-reservas-admin/', views.reservas_espaco_admin, name='menu-reservas-admin'),
    path('reserva/delete/<int:pk>', views.delete_reserva, name='delete-reserva'),
    path('list-reservas-exames-admin/', views.reservas_exames_admin, name='menu-reservas-exames-admin'),
    path('reserva-exame/delete/<int:pk>', views.delete_reserva_exames, name='delete-reserva-exame'),
    path('list-reservas/', views.reservas_espaco, name='list-reservas'),
    path('list-reservas-exames/', views.reservas_exames, name='menu-reservas-exames'),
    path('reserva-normal/delete/<int:pk>', views.delete_reserva_normal, name='delete-reserva-normal'),
    path('reserva-exame-normal/delete/<int:pk>', views.delete_reserva_exames_normal, name='delete-reserva-exame-normal'),
]

exames/urls.py
from django.urls import path

from . import views

app_name = 'exames'
urlpatterns = [        
    path('', views.exames, name='index'),
    path('dias/<int:pk>', views.detail_dia, name='detail-dia'),
    path('exame/confirmar/<int:pk>', views.create_reserva, name='create-reserva'),
]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'
urlpatterns = [        
    path('', views.perfil, name='index'),
    path('update_usuario/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
]

perfil/models.py
from django.db import models

# Create your models here.

perfil/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from django.contrib.auth.models import User, Group
from accounts.models import Clube, Atletica, Usuario


class UserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Usuario
        fields = ('is_active','username', 'email','nome','clube','atletica','foto')

perfil/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from .forms import UserChangeForm
from accounts.models import Clube, Atletica, Usuario



@login_required(redirect_field_name='login')
def perfil(request):  
    usuario = request.user
    grupo = usuario.groups
    reservas_exames = usuario.horario_exames_set.all()
    reservas = usuario.horario_set.all()
    
    context = {'usuario': usuario,
                'grupo': grupo,   
                'reservas': reservas,
                'reservas_exames': reservas_exames,   }   
    return render(request, 'perfil/perfil.html', context)



class UserUpdateView(generic.UpdateView):
    context_object_name = 'user'
    form_class = UserChangeForm
    model = Usuario
    template_class = UserChangeForm
    template_name = "perfil/update.html"

    def get_success_url(self):
        return reverse('perfil:index')

perfil/templates/perfil/perfil.html
{% extends 'base.html' %}

{% block title %}
Perfil de Usuário
{% endblock title %}

{% block content %}
<style>
    img {
      border-radius: 10%;
    }
</style>
<h1>Perfil de {{ usuario.username | safe }}</h1>

<div class = 'caixinha2'>
    <div class = 'foto'>
      {% if user.foto %}
        <img src="{{ usuario.foto }}" width="300" height="300">
      {% else %}
        <img src="https://i.imgur.com/XaB46bK.png" width="300" height="300">   
      {% endif %}   
    </div>
    <div>
      <h2>Nome:</h2> <i>{{ usuario.nome | safe }}</i>
      <br></br> <br></br>
      <h2>Telefone:</h2> <i>{{ usuario.telefone | safe }}</i>
    </div>
    <div>
      <h2>Clube:</h2> <i>{{ usuario.clube | safe }}</i>
      <br></br> <br></br>
      <h2>Atlética associada:</h2> <i>{{ usuario.atletica | safe }}</i>
    </div>
    <div>
      <h2>E-mail:</h2><i>{{ usuario.email | safe }}</i>
      <br></br> <br></br>
    </div>
    <div class="function">
      <h2> Minhas reservas </h2>
      <a href="{% url 'accounts:list-reservas' %}"><img src="https://i.imgur.com/uTvysWr.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
      <h2>Meus exames </h2> 
      <a href="{% url 'accounts:menu-reservas-exames' %}"><img src="https://i.imgur.com/mpGPN7T.png" width="100" height="100" alt="Reservas"></a>
    </div>
</div>
<br>
<div class = "caixinha3">
  <div class="function">
    Editar Perfil
    <a href="{% url 'perfil:update' usuario.id %}"><img src="https://i.imgur.com/2EtoEnL.png" width="100" height="100" alt="update"></a>
  </div>
</div>
{% endblock content %}

perfil/templates/perfil/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Modificar Usuario
{% endblock title %}

{% block content %}

<div id='update'>
<h1>Modificar perfil do usuário "{{ user.username | safe }}" </h1>
<form method="POST" action="{% url 'perfil:update' user.id%}">
    {% csrf_token %}
    Nome de usuário: {{form.username}}
    Nome: {{form.nome}}
    E-mail: {{form.email}}
    URL da Foto de Perfil: {{form.foto}}
    Clube: {{form.clube}}
    Atletica: {{form.atletica}}  <br></br>
    Para desativar sua conta, demarque a caixinha abaixo: <br></br> {{ form.is_active}}  <br></br>
    
    <button type="submit">Atualizar Perfil</button>
</form>
<button>
<a href="{% url 'perfil:index' %}">Cancelar</a>
</button>
</div>
{% endblock content %}