QQuadra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reservas/', include('reservas.urls')),
    path('exames/', include('exames.urls')),
    path('perfil/', include('perfil.urls')),
    path('gerenciar/', include('gerenciar.urls')),
]

accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('list/', views.list_users, name='list'),
    path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    path('menu-reservas/', views.menu_reservas_admin, name='menu-reservas'),
    path('list-reservas-admin/', views.reservas_espaco_admin, name='menu-reservas-admin'),
    path('reserva/delete/<int:pk>', views.delete_reserva, name='delete-reserva'),
    path('list-reservas-exames-admin/', views.reservas_exames_admin, name='menu-reservas-exames-admin'),
    path('reserva-exame/delete/<int:pk>', views.delete_reserva_exames, name='delete-reserva-exame'),
    path('list-reservas/', views.reservas_espaco, name='list-reservas'),
    path('list-reservas-exames/', views.reservas_exames, name='menu-reservas-exames'),
    path('reserva-normal/delete/<int:pk>', views.delete_reserva_normal, name='delete-reserva-normal'),
    path('reserva-exame-normal/delete/<int:pk>', views.delete_reserva_exames_normal, name='delete-reserva-exame-normal'),
]

exames/urls.py
from django.urls import path

from . import views

app_name = 'exames'
urlpatterns = [        
    path('', views.exames, name='index'),
    path('dias/<int:pk>', views.detail_dia, name='detail-dia'),
    path('exame/confirmar/<int:pk>', views.create_reserva, name='create-reserva'),
]

gerenciar/urls.py
from django.urls import path

from . import views

app_name = 'gerenciar'
urlpatterns = [        
    path('', views.gerenciar, name='index'),
    path('resetar/', views.resetar, name='resetar'),
    path('resetar/exames/', views.resetar_exames, name='resetar-exames'),
    path('atualizar/', views.atualizar, name='atualizar'),
    path('atualizar/exames/', views.atualizar_exames, name='atualizar-exames'),
    path('gerenciar/modalidades/', views.modalidades_list, name='lista-modalidades'),
    path('gerenciar/material/<int:pk>', views.material_list, name='lista-material'),
    path('gerenciar/material/estoque/<int:pk>', views.material_estoque, name='estoque-meterial'),
    path('gerenciar/material/estoque/update/<int:pk>', views.update_estoque, name='update-estoque'),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from django.contrib.postgres.fields import ArrayField



class Modalidade(models.Model):    
    name = models.CharField(max_length=255)  
    icon_url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'



class Clube(models.Model):
    name = models.CharField(max_length=255)
    DESCR = models.TextField()
    adress = models.TextField()
    horario_inicial = models.TimeField()
    horario_final = models.TimeField()
    modalidades = models.ManyToManyField(Modalidade)

    def __str__(self):
        return f'{self.name}'



class Atletica(models.Model):    
    nome = models.CharField(max_length=255)
    instituicao = models.CharField(max_length=255)
    
    def __str__(self):
        return f'{self.nome}'



class Usuario(AbstractUser):    
    nome = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.IntegerField( blank=True, null=True)
    foto = models.URLField(blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    clube = models.ForeignKey(Clube, on_delete=models.CASCADE, blank=True, null=True)
    atletica = models.ForeignKey(Atletica, on_delete=models.CASCADE, blank=True, null=True)
    is_active = models.BooleanField(default=False)



class EspacoEsportivo(models.Model):    
    DESCR = models.TextField()
    modalidade = models.ForeignKey(Modalidade, on_delete=models.CASCADE)
    clube = models.ForeignKey(Clube, on_delete=models.CASCADE)  
    foto = models.URLField(blank=True, null=True)  

    def __str__(self):
        return (f'{self.DESCR} {self.clube}')



class TipoMaterial(models.Model):    
    DESCR = models.TextField()
    name = models.CharField(max_length=255)
    modalidade = models.ForeignKey(Modalidade, on_delete=models.CASCADE) 
    foto = models.URLField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'



class EstoqueMaterial(models.Model):    
    quantidade = models.IntegerField() 
    tipo_material = models.ForeignKey(TipoMaterial, on_delete=models.CASCADE)
    clube = models.ForeignKey(Clube, on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.tipo_material} {self.clube}'




class Dia(models.Model):
    espaco = models.ForeignKey(EspacoEsportivo, on_delete=models.CASCADE)
    dia = models.DateField()
    
    def __str__(self):
        return f'{self.dia} {self.espaco}'



class Horario(models.Model):
    dia = models.ForeignKey(Dia, on_delete=models.CASCADE)
    horario = models.TimeField()
    livre = models.BooleanField(default=False)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE,blank=True, null=True)
    
    def __str__(self):
        return f'{self.dia} {self.horario}'



class Dia_Exames(models.Model):
    clube = models.ForeignKey(Clube, on_delete=models.CASCADE)
    dia = models.DateField()
    
    def __str__(self):
        return f'{self.dia} {self.clube}'



class Horario_Exames(models.Model):
    dia = models.ForeignKey(Dia_Exames, on_delete=models.CASCADE)
    horario = models.TimeField()
    livre = models.BooleanField(default=False)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE,blank=True, null=True)
    
    def __str__(self):
        return f'{self.dia} {self.horario}'

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from django.contrib.auth.models import User, Group
from .models import Clube, Atletica, Usuario


class UserGroupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Usuario
    nome = forms.CharField(label = "Nome")
    telefone = forms.CharField(label = "Telefone")
    foto = forms.URLField(label = "URL da Foto de Perfil",required=False)
    email = forms.CharField(label = "Endereço de E-mail")
    type = forms.ChoiceField(choices=(("publico","Público"),("atletica","Atlética")), required=True, label="Tipo de Conta")
    clube = forms.ModelChoiceField(queryset=Clube.objects.all(), required=True)
    atletica = forms.ModelChoiceField(queryset=Atletica.objects.all(), required=False, label = "Atlética")

    def save(self, commit=True):
        user = super(UserGroupForm, self).save(commit=False)
        user.nome = self.cleaned_data["nome"]
        user.telefone = self.cleaned_data["telefone"]
        user.foto = self.cleaned_data["foto"]
        user.email = self.cleaned_data["email"]
        user.type = self.cleaned_data["type"]
        user.clube = self.cleaned_data["clube"]
        user.atletica = self.cleaned_data["atletica"]
        

        if commit:
            user.save()
        return user
    
class UserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Usuario
        fields = ('is_active','username', 'email','nome','groups','clube','atletica')

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import Group
from .forms import UserGroupForm,UserChangeForm
from .models import Usuario,Horario,Horario_Exames
from django.contrib.auth.decorators import login_required
from django.views import generic
from .decorators import allowed_users



def signup(request):
    if request.method == 'POST':
        form = UserGroupForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_group = Group.objects.get(name=user.type)
            user.groups.add(user_group)  
            return HttpResponseRedirect(reverse('login'))
    else:
        form = UserGroupForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)



def logoutUser(request):
	logout(request)
	return redirect('login')



@login_required
@allowed_users(allowed_roles=['admin'])
def list_users(request):
    usuario = request.user
    clube=usuario.clube
    users_list = Usuario.objects.filter(clube=clube.id)
    context = {'users_list': users_list}
    
    return render(request, 'accounts/list.html', context)



def menu_reservas_admin(request):
    return render(request, 'accounts/menu-reservas-admin.html')



def reservas_espaco_admin(request):
    clube = request.user.clube
    horarios = Horario.objects.filter(livre=True)
    context = {'clube': clube,
                'horarios': horarios,}

    return render(request, 'accounts/list-reservas-admin.html',context)



def delete_reserva(request,pk):
    horario = get_object_or_404(Horario, pk=pk)
    if request.method == "POST":
        horario.livre = False
        horario.usuario = None
        horario.save()
        return HttpResponseRedirect(reverse('accounts:menu-reservas-admin'))

    context = {'horario': horario}
    return render(request, 'accounts/delete-reserva.html', context)



def reservas_exames_admin(request):
    clube = request.user.clube
    horarios = Horario_Exames.objects.filter(livre=True)
    context = {'clube': clube,
                'horarios': horarios,}
    
    return render(request, 'accounts/list-reservas-exames-admin.html',context)



def delete_reserva_exames(request,pk):
    horario = get_object_or_404(Horario_Exames, pk=pk)
    if request.method == "POST":
        horario.livre = False
        horario.usuario = None
        horario.save()
        return HttpResponseRedirect(reverse('accounts:menu-reservas-exames-admin'))

    context = {'horario': horario}
    return render(request, 'accounts/delete-reserva-exames.html', context)



def reservas_espaco(request):
    clube = request.user.clube
    usuario = request.user
    horarios = Horario.objects.filter(livre=True,usuario=usuario.id)
    context = {'clube': clube,
                'horarios': horarios,}
    
    return render(request, 'accounts/list-reservas.html',context)



def reservas_exames(request):
    clube = request.user.clube
    usuario = request.user
    horarios = Horario_Exames.objects.filter(livre=True,usuario=usuario.id)
    context = {'clube': clube,
                'horarios': horarios,}
    
    return render(request, 'accounts/list-reservas-exames.html',context)



def delete_reserva_normal(request,pk):
    horario = get_object_or_404(Horario, pk=pk)
    if request.method == "POST":
        horario.livre = False
        horario.usuario = None
        horario.save()
        return HttpResponseRedirect(reverse('accounts:list-reservas'))

    context = {'horario': horario}
    return render(request, 'accounts/delete-reserva-normal.html', context)



def delete_reserva_exames_normal(request,pk):
    horario = get_object_or_404(Horario_Exames, pk=pk)
    if request.method == "POST":
        horario.livre = False
        horario.usuario = None
        horario.save()
        return HttpResponseRedirect(reverse('accounts:menu-reservas-exames'))

    context = {'horario': horario}
    return render(request, 'accounts/delete-reserva-exames-normal.html', context)



class UserUpdateView(generic.UpdateView):
    context_object_name = 'user'
    form_class = UserChangeForm
    model = Usuario
    template_class = UserChangeForm
    template_name = "accounts/update.html"

    def get_success_url(self):
        return reverse('accounts:list')



class UserDeleteView(generic.DeleteView):
    model = Usuario
    context_object_name = 'user'
    template_name = 'accounts/delete.html'

    def get_success_url(self):
        return reverse('accounts:list')

accounts/templates/accounts/delete-reserva-exames-normal.html
{% extends 'base.html' %}

{% block title %}
Apagar Exame
{% endblock title %}

{% block content %}
<form action="{% url 'accounts:delete-reserva-exame-normal' horario.id %}" method="post">
    {% csrf_token %}
    <h1>Apagar Exame</h1>
    <div class = "caixinha1">
    <li><b>Clube:</b> {{horario.dia.clube.name | safe}}</li>
    <li><b>Dia:</b> {{ horario.dia.dia | date }}</li>
    <li><b>Horário:</b> {{ horario.horario }}</li>
    </div>
    <br></br>
    <h3>Deseja Apagar esse Exame?</h3>

    <button type="submit">Sim</button>
</form>

{% endblock content %}

accounts/templates/accounts/delete-reserva-exames.html
{% extends 'base.html' %}

{% block title %}
Apagar Exame
{% endblock title %}

{% block content %}
<form action="{% url 'accounts:delete-reserva-exame' horario.id %}" method="post">
    {% csrf_token %}
    <h1>Apagar Exame</h1>
    <div class = "caixinha1">
    <li><b>Clube:</b> {{horario.dia.clube.name | safe}}</li>
    <li><b>Dia:</b> {{ horario.dia.dia | date }}</li>
    <li><b>Horário:</b> {{ horario.horario }}</li>
    <li><b>Nome:</b> {{ horario.usuario.nome }}</li>
    </div>
    <br></br>
    <h3>Deseja Apagar esse Exame?</h3>

    <button type="submit">Sim</button>
</form>

{% endblock content %}

accounts/templates/accounts/delete-reserva-normal.html
{% extends 'base.html' %}

{% block title %}
Apagar Reserva
{% endblock title %}

{% block content %}
<form action="{% url 'accounts:delete-reserva-normal' horario.id %}" method="post">
    {% csrf_token %}
    <h1>Apagar Reserva</h1>
    <div class = "caixinha1">
    <li><b>Clube:</b> {{horario.dia.espaco.clube.name | safe}}</li>
    <li><b>Modalidade:</b> {{ horario.dia.espaco.modalidade.name | safe }}</li>
    <li><b>Espaço:</b> {{ horario.dia.espaco.DESCR | safe }}</li>
    <li><b>Dia:</b> {{ horario.dia.dia | date }}</li>
    <li><b>Horário:</b> {{ horario.horario }}</li>
    </div>
    <br></br>
    <h3>Deseja Apagar essa Reserva?</h3>

    <button type="submit">Sim</button>
</form>

{% endblock content %}

accounts/templates/accounts/delete-reserva.html
{% extends 'base.html' %}

{% block title %}
Apagar Reserva
{% endblock title %}

{% block content %}
<form action="{% url 'accounts:delete-reserva' horario.id %}" method="post">
    {% csrf_token %}
    <h1>Apagar Reserva</h1>
    <div class = "caixinha1">
    <li><b>Clube:</b> {{horario.dia.espaco.clube.name | safe}}</li>
    <li><b>Modalidade:</b> {{ horario.dia.espaco.modalidade.name | safe }}</li>
    <li><b>Espaço:</b> {{ horario.dia.espaco.DESCR | safe }}</li>
    <li><b>Dia:</b> {{ horario.dia.dia | date }}</li>
    <li><b>Horário:</b> {{ horario.horario }}</li>
    <li><b>Nome:</b> {{ horario.usuario.nome }}</li>
    </div>
    <br></br>
    <h3>Deseja Apagar essa Reserva?</h3>

    <button type="submit">Sim</button>
</form>

{% endblock content %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block title %}
Apagar Usuário
{% endblock title %}

{% block content %}
<form action="{% url 'accounts:delete' user.id %}" method="post">
    {% csrf_token %}
    
        <br></br>
        Você tem certeza que deseja apagar o usuário "{{ user.username | safe }}"?
        <br></br>
    
    <button type="submit">Apagar</button>
    <button>
    <a href="{% url 'accounts:list' %}">Cancelar</a>
    </button>
</form>

{% endblock content %}

accounts/templates/accounts/list-reservas-admin.html
{% extends 'base.html' %}

{% block title %}
Reservas
{% endblock title %}

{% block content %}
<h1>Reservas</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
</div>
<br></br>


{% if horarios %}
    <table>
        <thead>
            <tr>
                <th>Clube</th>
                <th>Modalidade</th>
                <th>Espaço Esportivo</th>
                <th>Dia</th>
                <th>Horário</th>
                <th>Reservado Por</th>
                <th>Telefone</th>
                <th>E-mail</th>
                <th>Modificar</th>
            </tr>
        </thead>
        <tbody>
            {% for horario in horarios.all %}
            <tr>
                
                <td>{{ horario.dia.espaco.clube.name | safe  }}</td>
                <td>{{ horario.dia.espaco.modalidade | safe  }}</td>
                <td>{{ horario.dia.espaco.DESCR   }}</td>
                <td>{{ horario.dia.dia | date }}</td>
                <td>{{ horario.horario | time }}</td>
                <td>{{ horario.usuario.username | safe }}</td>
                <td>{{ horario.usuario.telefone | safe }}</td>
                <td>{{ horario.usuario.email | safe }}</td>
                <td><a href="{% url 'accounts:delete-reserva' horario.id %}">Apagar</a></td>
                
            
            </tr>  
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Não foi encontrado nenhum horário</p>
{% endif %}

{% endblock content %}

accounts/templates/accounts/list-reservas-exames-admin.html
{% extends 'base.html' %}

{% block title %}
Reservas
{% endblock title %}

{% block content %}
<h1>Reservas</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
</div>
<br></br>


{% if horarios %}
    <table>
        <thead>
            <tr>
                <th>Clube</th>
                <th>Dia</th>
                <th>Horário</th>
                <th>Reservado Por</th>
                <th>Telefone</th>
                <th>E-mail</th>
                <th>Modificar</th>
            </tr>
        </thead>
        <tbody>
            {% for horario in horarios.all %}
            <tr>
                
                <td>{{ horario.dia.clube.name | safe  }}</td>
                <td>{{ horario.dia.dia | date }}</td>
                <td>{{ horario.horario | time }}</td>
                <td>{{ horario.usuario.username | safe }}</td>
                <td>{{ horario.usuario.telefone | safe }}</td>
                <td>{{ horario.usuario.email | safe }}</td>
                <td><a href="{% url 'accounts:delete-reserva-exame' horario.id %}">Apagar</a></td>
                
            
            </tr>  
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Não foi encontrado nenhum horário</p>
{% endif %}

{% endblock content %}

accounts/templates/accounts/list-reservas-exames.html
{% extends 'base.html' %}

{% block title %}
Reservas
{% endblock title %}

{% block content %}
<h1>Suas Reservas de Exame Médico</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
</div>
<br></br>

{% if horarios %}
    <table>
        <thead>
            <tr>
                <th>Clube</th>
                <th>Dia</th>
                <th>Horário</th>
                <th>Modificar</th>
            </tr>
        </thead>
        <tbody>
            {% for horario in horarios.all %}
                <tr>
                    
                    <td>{{ horario.dia.clube.name | safe  }}</td>
                    <td>{{ horario.dia.dia | date }}</td>
                    <td>{{ horario.horario | time }}</td>
                    <td><a href="{% url 'accounts:delete-reserva-exame-normal' horario.id %}">Apagar</a></td>
                    
                
                </tr>  
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Não foi encontrado nenhum horário</p>
{% endif %}

{% endblock content %}

accounts/templates/accounts/list-reservas.html
{% extends 'base.html' %}

{% block title %}
Reservas
{% endblock title %}

{% block content %}
<h1>Suas Reservas de Espaço Esportivo</h1>
<div class = "caixinha1">
<li><b>Clube:</b> {{clube.name | safe}}</li>
</div>
<br></br>

{% if horarios %}
    <table>
        <thead>
            <tr>
                <th>Clube</th>
                <th>Modalidade</th>
                <th>Espaço Esportivo</th>
                <th>Dia</th>
                <th>Horário</th>
                <th>Modificar</th>
            </tr>
        </thead>
        <tbody>
            {% for horario in horarios.all %}
                <tr>
                    
                    <td>{{ horario.dia.espaco.clube.name | safe  }}</td>
                    <td>{{ horario.dia.espaco.modalidade | safe  }}</td>
                    <td>{{ horario.dia.espaco.DESCR   }}</td>
                    <td>{{ horario.dia.dia | date }}</td>
                    <td>{{ horario.horario | time }}</td>
                    <td><a href="{% url 'accounts:delete-reserva-normal' horario.id %}">Apagar</a></td>
                    
                
                </tr>  
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Não foi encontrado nenhum horário</p>
{% endif %}

{% endblock content %}

accounts/templates/accounts/list.html
<!--- página onde o ADM da empresa pode analisar as requisições de cadastro de novos usuários--->
<!--- desta você pode ir para INDEX-ADM --->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="req">
<h1>Administração de usuários</h1>

{% if users_list %}
    <div id='tabela'>
    <table >
        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Usuário</th>
                <th>Grupo</th>
                <th>Status</th>
                <th>Edição de usuário</th>
                <th>Remoção</th>
            </tr>
        </thead>
        {% for user in users_list %}
            {% if not user.is_superuser %}
                <tbody>
                    <tr>
                        <td>{{user.nome}}</td>
                        <td>{{user.email}}</td>
                        <td>{{user.username}}</td>
                        <td>{{user.groups.all.0}}</td>
                        <td>{% if user.is_active %}
                                <p class="status_ativo" >Ativo</p>
                            {% else %}
                                <p class="status_inativo">Inativo</p>
                            {% endif %}
                        </td>
                        <td><a  href="{% url 'accounts:update' user.id %}">Editar</a></td>
                        <td><a class="del"href="{% url 'accounts:delete' user.id %}">Deletar</a></td>
                    </tr>
                </tbody>
            {% endif %}
        {% endfor %}
    </table> 
    </div>
{% else %}
    <p>Não há nenhum colaborador registrado.</p>
{% endif %}

<ul><a href="{% url 'gerenciar:index' %}">Voltar ao menu</a></ul>
</div>

{% endblock %}

accounts/templates/accounts/menu-reservas-admin.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1>Menu de Funções</h1>

<div class="functionMenu">
    <div class="function">
        Reservas Espaços <br>
        <a href="{% url 'accounts:menu-reservas-admin' %}"><img src="https://i.imgur.com/uTvysWr.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Reservas Exames <br>
        <a href="{% url 'accounts:menu-reservas-exames-admin' %}"><img src="https://i.imgur.com/mpGPN7T.png" width="100" height="100" alt="Exame"></a>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
Criar Usuário
{% endblock title %}

{% block content %}
<h1>Criar Usuário</h1>

<form method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %} 

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div id='update'>
<h1>Mudar status do usuário "{{ user.username | safe }}" </h1>
<form method="POST" action="{% url 'accounts:update' user.id%}">
    {% csrf_token %}
    Nome de usuário: {{form.username}}
    Nome: {{form.nome}}
    E-mail: {{form.email}}
    Grupo: {{form.groups}}
    Clube: {{form.clube}}
    Atletica: {{form.atletica}}
    <br></br>
    Atualmente o usuário encontra-se
    {% if user.is_active %}
        ativo. <br> Para desativá-lo, basta desmarcar a caixa de seleção abaixo.
        <br></br>
    {% else %}
        inativo. <br> Para ativá-lo, basta marcar a caixa de seleção abaixo.
        <br></br>
    {% endif %}
    {{ form.is_active}}
    <br></br>
    <button type="submit">Atualizar status</button>
</form>
<button>
<a href="{% url 'accounts:list' %}">Cancelar</a>
</button>
</div>
{% endblock content %}