QQuadra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reservas/', include('reservas.urls')),
    path('exames/', include('exames.urls')),
    path('perfil/', include('perfil.urls')),
    path('gerenciar/', include('gerenciar.urls')),
]

exames/urls.py
from django.urls import path

from . import views

app_name = 'exames'
urlpatterns = [        
    path('', views.exames, name='index'),
    path('dias/<int:pk>', views.detail_dia, name='detail-dia'),
    path('exame/confirmar/<int:pk>', views.create_reserva, name='create-reserva'),
]

gerenciar/urls.py
from django.urls import path

from . import views

app_name = 'gerenciar'
urlpatterns = [        
    path('', views.gerenciar, name='index'),
    path('resetar/', views.resetar, name='resetar'),
    path('resetar/exames/', views.resetar_exames, name='resetar-exames'),
    path('atualizar/', views.atualizar, name='atualizar'),
    path('atualizar/exames/', views.atualizar_exames, name='atualizar-exames'),
    path('gerenciar/modalidades/', views.modalidades_list, name='lista-modalidades'),
    path('gerenciar/material/<int:pk>', views.material_list, name='lista-material'),
    path('gerenciar/material/estoque/<int:pk>', views.material_estoque, name='estoque-meterial'),
    path('gerenciar/material/estoque/update/<int:pk>', views.update_estoque, name='update-estoque'),
    
]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'
urlpatterns = [        
    path('', views.perfil, name='index'),
    path('update_usuario/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
]

reservas/urls.py
from django.urls import path

from . import views

app_name = 'reservas'
urlpatterns = [        
    path('', views.reservas, name='index'),
    path('<int:modalidade_id>/', views.detail_modalidade, name='detail'),
    path('espaco/<int:espaco_id>/', views.detail_espaco, name='detail-espaco'),
    path('espaco/dia/<int:pk>', views.detail_dia, name='detail-dia'),
    path('espaco/confirmar/<int:pk>', views.create_reserva, name='create-reserva'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

staticpages/models.py
from django.db import models

# Create your models here.

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}

<h1>Sobre o Site</h1>
<div class = 'caixinha'>
<p>
    QQuadra é uma plataforma para gerenciamente de reservas de clubes esportivos. Este site foi
    elaborado como requisito avaliativo para a disciplina PMR3304 - Sistemas de Informação, no
    curso de Engenharia Mecatrônica da Escola Politécnica da Universidade de São Paulo.
</p>
</div>
<h1></h1>
<a href="https://www.poli.usp.br/"><img src="https://imagens.usp.br/wp-content/uploads/EP-Escrita.jpg" width="400" height="100"></a>
<h1></h1>
<h2>Sobre os Autores</h2>

<div class = 'caixinha1'>
    <b>Site desenvolvido por:</b>
    <b></b>
    <i>Emanuel Iwanow de Araujo (NºUSP: 11257932)</i>
    <i>Gabriel Antonio Corteletti Tápias (NºUSP: 11258210)</i>
    <i>Gustavo Geraldo de Andrade Melo (NºUSP: 11258183)</i>
    <i>Júlio César Rodrigues Alves Paz (NºUSP: 11257911)</i>
</div>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1>Menu de Funções</h1>

<div class="functionMenu">
    <div class="function">
        Reservas <br>
        <a href="{% url 'reservas:index' %}"><img src="https://i.imgur.com/uTvysWr.png" width="100" height="100" alt="Reservas"></a>
    </div>
    <div class="function">
        Exames <br>
        <a href="{% url 'exames:index' %}"><img src="https://i.imgur.com/mpGPN7T.png" width="100" height="100" alt="Exame"></a>
    </div>
    <div class="function">
        Materiais <br>
        <a href="{% url 'gerenciar:lista-modalidades' %}"><img src="https://i.imgur.com/No7mqY8.png" width="100" height="100" alt="Materiais"></a>
    </div>
    <div class="function">
        Perfil <br>
        <a href="{% url 'perfil:index' %}"><img src="https://i.imgur.com/sUX9TVd.png" width="100" height="100" alt="Perfil"></a>
    </div>
    <div class="function">
        Gerenciar <br>
        <a href="{% url 'gerenciar:index' %}"><img src="https://i.imgur.com/2EtoEnL.png" width="100" height="100" alt="Gerenciar"></a>
    </div>
    
</div>
<h1></h1>
<div class="row"> 
    <div class="column">
        <img  src="https://i.imgur.com/6SzVpUj.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/KrCTvQG.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/aFhJCip.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pHd22oY.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/f2ayYpE.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/ZeRWOmp.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/9fwRCMn.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/4tNs75x.jpg"
            style="width:100%">
    </div>
    <div class="column">
        <img  src="https://i.imgur.com/eYQ4Teo.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/sGsw4oH.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/fD6ETdm.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/MxXbgMD.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/12ANO1S.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/ilNSuAk.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/Sy9IkDx.jpg"
            style="width:100%">
        </div>
    <div class="column">
        <img  src="https://i.imgur.com/5H6SoGb.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/IxKN6s9.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pLFYhBZ.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/AQqKHmU.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/Y9Qbx4p.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/qrvpHkI.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pNvmoDX.jpg"
            style="width:100%">
    </div>
  </div>
{% endblock content %}